name: Build debian packages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-deb-packages:
    name: Ubuntu Devel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Yaru code
        uses: actions/checkout@v4

      - name: Build debian packages and sources
        uses: canonical/desktop-engineering/gh-actions/common/build-debian@main
        with:
          docker-image: ubuntu:devel
